// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @returns {Promise.<void>}
 */
export async function AskFavouriteColor() {
	// BEGIN USER CODE
	return new Promise((resolve)=>{
		const SpeechRecognition = SpeechRecognition 
			|| webkitSpeechRecognition;
		let recognition = new SpeechRecognition();
		let pid;

		recognition.lang = "en-US";
		recognition.continuous = false;
		recognition.interimResults = false;
		recognition.maxAlternatives = 1;
		recognition.onresult = function(result){
			// do something with result
			const spokenColour = result.results[0][0].transcript;
			const confidence = result.results[0][0].confidence;
			console.log(spokenColour);
			mx.ui.hideProgress(pid);
			resolve({
				colour: spokenColour,
				confidence: confidence
			});
		}
		recognition.start();
		pid = mx.ui.showProgress("Now listening for your favourite colour...");
	});
	
	// throw new Error("JavaScript action was not implemented");
	// END USER CODE
}
