// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";
import { AskFavouriteColor } from "./AskFavouriteColor.js"

// BEGIN EXTRA CODE
async function createMendixObject() {
	return new Promise((resolve) => {
		mx.data.create({
			entity: "FrontEndWorkshop.ColourConfidence",
			callback: (newObject) => { resolve(newObject); },
			error: (e) => { console.log(e) }
		})
	})
}
// END EXTRA CODE

/**
 * @returns {Promise.<MxObject>}
 */
export async function GetColourWithConfidence() {
	// BEGIN USER CODE
	const res = await AskFavouriteColor();
	const newObj = await createMendixObject();
	newObj.set("Colour", res.colour);
	newObj.set("Confidence", new Big(res.confidence).toFixed(4));
	return newObj;
	// END USER CODE
}
