// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";
import { AskFavouriteColor } from "./AskFavouriteColor.js"

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {string} allowedColors - add a comma-separated list
 * @returns {Promise.<string>}
 */
export async function GetFavouriteColour(allowedColors) {
	// BEGIN USER CODE
	const result = await AskFavouriteColor();
	if (allowedColors.split(',').find((o) => { return o === result.colour })) {
		return result.colour;
	}
	else return null;


	// throw new Error("JavaScript action was not implemented");
	// END USER CODE
}
