// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";
import Person, { MyJSFunction } from "./MyJSFunction"; // 1. another JS action
import Animal from "../../share.js"; // 2. any file accessible from the javascriptsource dir
import ThemeFunc from "../../../theme/themejs.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @returns {Promise.<void>}
 */
export async function ImportsTest() {
	// BEGIN USER CODE
	await MyJSFunction();
	const person = new Person("Conner");
	person.sayHi();
	const oona = new Animal("dog", "Oona");
	console.log(oona.getInfo())
	gvar.globalFunc(); // 3. gloablly declared variable
	ThemeFunc();
	// throw new Error("JavaScript action was not implemented");
	// END USER CODE
}
