// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";

// BEGIN EXTRA CODE
function sayHello() {
	console.log("hello");
}
// END EXTRA CODE

/**
 * @param {string} myName - The name to log
 * @param {Big} myAge - My Age
 * @returns {Promise.<void>}
 */
export async function JS_HelloWorld(myName, myAge) {
	// BEGIN USER CODE
	console.log(`Hello ${myName}`); // ES6 String Template Notation
	console.log("Hello " + myName); // JS String Concatenation
	sayHello(); // example of using "extra code" fence
	return Promise.resolve();
	// throw new Error("JavaScript action was not implemented");
	// END USER CODE
}
