// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";

// BEGIN EXTRA CODE
export default class Person{
	constructor(name){
		this.name = name;
	}
	sayHi(){
		console.log(`Hello ${this.name}`);
	}
}
// END EXTRA CODE

/**
 * @returns {Promise.<void>}
 */
export async function MyJSFunction() {
	// BEGIN USER CODE
	console.log("Hello from My JS Function");
	return Promise.resolve();
	// throw new Error("JavaScript action was not implemented");
	// END USER CODE
}
